import pytest

docker = pytest.importorskip("docker")

from checkpoint.docker.harness_image import build_harness_image, HarnessImageError


@pytest.fixture
def docker_client():
    try:
        client = docker.from_env()
        client.ping()
    except Exception:
        pytest.skip("docker daemon not available")
    return client


def _cleanup(client, tag):
    try:
        client.images.remove(tag, force=True)
    except Exception:
        pass


def test_explicit_dockerfile_is_built(tmp_path, docker_client):
    (tmp_path / "Dockerfile").write_text(
        "FROM alpine:3.19\nLABEL checkpoint_test=explicit\nCMD [\"true\"]\n"
    )
    tag = "checkpoint-test-harness-explicit:latest"
    try:
        out = build_harness_image(tmp_path, None, tag)
        assert out == tag
        image = docker_client.images.get(tag)
        assert image.labels.get("checkpoint_test") == "explicit"
    finally:
        _cleanup(docker_client, tag)


def test_python_runtime_is_autogenerated(tmp_path, docker_client):
    (tmp_path / "requirements.txt").write_text("")
    (tmp_path / "harness.py").write_text('print("hi")\n')
    tag = "checkpoint-test-harness-python:latest"
    try:
        out = build_harness_image(tmp_path, "python harness.py", tag)
        assert out == tag
        image = docker_client.images.get(tag)
        cmd = image.attrs["Config"]["Cmd"]
        assert "harness.py" in cmd
    finally:
        _cleanup(docker_client, tag)


def test_unknown_runtime_raises(tmp_path, docker_client):
    with pytest.raises(HarnessImageError) as excinfo:
        build_harness_image(tmp_path, None, "checkpoint-test-harness-empty:latest")
    msg = str(excinfo.value)
    assert "Dockerfile" in msg
    assert "requirements.txt" in msg or "pyproject.toml" in msg
